# Generated by Django 5.2.16 on 2026-08-03 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('skill', 'Skill'), ('value', 'Value'), ('trait', 'Trait')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('synergy', 'Synergy'), ('tension', 'Tension')], max_length=10)),
                ('weight', models.FloatField(help_text='Strength rating in [0, 1] from the pairwise mapping phase.')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='graph.item')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='graph.item')),
            ],
            options={
                'unique_together': {('source', 'target')},
            },
        ),
    ]
