# Generated by Django 5.2.16 on 2026-08-03 11:15

import django.db.models.deletion
import participant_sessions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgic', models.CharField(default=participant_sessions.models.generate_sgic, editable=False, max_length=8, unique=True)),
                ('pid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('classroom_code', models.CharField(blank=True, max_length=32)),
                ('tool_type', models.CharField(choices=[('adult_variant_a', 'Adult Future Work Self — Variant A (Guided Revision)'), ('adult_variant_b', 'Adult Future Work Self — Variant B (Redo Baseline)'), ('youth', 'Youth Career & Future Self Explorer'), ('leadership', 'Adult Leadership Identity Tool')], default='adult_variant_a', max_length=20)),
                ('current_phase', models.PositiveSmallIntegerField(choices=[(1, 'Card Discovery & Refinement'), (3, 'Importance Rating'), (4, 'Pairwise Synergy/Tension Mapping'), (5, 'Qualtrics Survey Redirect'), (6, 'Visual Feedback Report')], default=1)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=15)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_sessions', to='participant_sessions.session')),
            ],
        ),
    ]
